### PR TITLE
Adding CRC check

### PR DESCRIPTION
**Pull request by PetrDa**
Hi Rob, I have added crc check.
I have tested in only for positive case, ie. on receiving correct data from SHT.
Thanks for providing great small code for async reading SHT.
Petr

### CODE REVIEW

**Comment by RobTillaart** [comment]
Hi Petr,

The changes look good, and I will merge them asap.
I understand it is hard to generate a failing CRC without writing a SHT31 simulator.
I wrote one for the DHT22 and I can say it is a small project in itself.

Q: On which platform(s) did you test the code?


----
**Next major release?**
There are in fact two CRC's tested.  This triggered some thinking.
Assume that only one (e.g. H) fails and the other (T) is OK, then one might want keep the T value and ignore the H. The boolean return value cannot indicate which one failed or both. One would need 4 values to represent all possible return values, or a separate **error** variable. It would make code only slightly more complex. A serious drawback is it would break the interface of **readData()** which now returns a bool. As I prefer simplicity and maintainability the code below is more a thought / option for a next major release.

```cpp
#define SHT31_OK        0
#define SHT31_CRC_T     1
#define SHT31_CRC_H     2
#define SHT31_CRC_HT    3

...

uint8_t SHT31::readData(bool fast)
{
  uint8_t buffer[6];
  readBytes(6, (uint8_t*) &buffer[0]);

  uint8_t returnValue = SHT31_OK;

  if (fast || (buffer[2] == crc8(buffer, 2)) )
  {
    uint16_t raw = (buffer[0] << 8) + buffer[1];
    temperature = raw * (175.0 / 65535) - 45;
  }
  else returnValue |= SHT31_CRC_T;

  if (fast || (buffer[5] == crc8(buffer + 3, 2)) )
  {
    uint16_t raw = (buffer[3] << 8) + buffer[4];
    humidity = raw * (100.0 / 65535);
  }
  else returnValue |= SHT31_CRC_H;

  _lastRead = millis();	  _lastRead = millis();

  return returnValue;
}
```

**Comment by PetrDa** [comment]
Hi Rob,

I have tested it on WemosD1 with ESP8266, also in configuration with two SHT30 on two addresses.

In most of situations reading is reliable and it is simpler to repeat whole reading when one of CRC checks fails.
The beauty of your code is shortness and simple usage.

The question is how many people will be affected by change of return value type from bool to uint8_t when compiling with a new library version.

I can imagine that reading only one value could be used in noisy systems when chance to have both values correct is small.
Then could be possibility to have two additional functions returning bool, each reading taking only half of data and checking one CRC.
(In case compiler compiles only methods that are used in the main code this would keep the code smallest possible for reliable scenarios
and usable for noisy scenarios, but have no idea if real compilers are so good as I expect).

Next week (I hope) I will test SHT30 with much longer cable with different I2C frequencies.
Then I am sure some bit gets noisy and I have a chance to test CRC check in reality.
Or at least I apply some XOR operation on received data to verify CRC check failure.

Maybe would be good also to modify async example to demonstrate the usage of bool result of readData method.
Or usage of uint8_t return value if you decide for your version.
Anyway I will be happy to use any of possible versions.

Petr

**Comment by RobTillaart** [comment]
Thanks for your comments, they make perfect sense

In a noisy environment one should read the two parameters separately. That requirement would affect the code quite a bit, however that said if the line is that noisy one should consider other types of communication lines. A compiler can't possibly know if or when communication is noisy. 

So I go for **bool dataRead()**, either T & H are both good or you need a read both again. Keep it simple.

I will have a look at the async example too,

Thanks,

**Comment by RobTillaart** [comment]
> Maybe would be good also to modify async example to demonstrate the usage of bool result of readData method.

done

**Pull request merged**
